# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: protoc-gen-connect-go-servicestruct
    main: ./cmd/protoc-gen-connect-go-servicestruct
    binary: protoc-gen-connect-go-servicestruct
    skip: '{{ ne .Env.BUILD_COMPONENT "protoc-gen-connect-go-servicestruct" }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: protoc-gen-elixir-grpc
    main: ./cmd/protoc-gen-elixir-grpc
    binary: protoc-gen-elixir-grpc
    skip: '{{ ne .Env.BUILD_COMPONENT "protoc-gen-elixir-grpc" }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: protoc-gen-pony
    main: ./cmd/protoc-gen-pony
    binary: protoc-gen-pony
    skip: '{{ ne .Env.BUILD_COMPONENT "protoc-gen-pony" }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - cmd/*/README.md
      - cmd/*/CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Branch }}-{{ .ShortCommit }}-snapshot"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge remote-tracking branch"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: TrogonStack
    name: protoc-gen
  draft: false
  prerelease: auto
  mode: append
  name_template: "{{.Tag}}"
