package main

import (
	"bytes"
	"io"
	"os"
	"os/exec"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestVersion(t *testing.T) {
	t.Parallel()
	stdout, stderr, exitCode := testRunProtocGenElixirGrpc(t, nil, "--version")
	assert.Equal(t, "", stderr.String())
	assert.Equal(t, 0, exitCode)
	assert.Contains(t, stdout.String(), "protoc-gen-elixir-grpc")
	assert.Contains(t, stdout.String(), "commit:")
	assert.Contains(t, stdout.String(), "built:")
}

func TestHelp(t *testing.T) {
	t.Parallel()
	stdout, stderr, exitCode := testRunProtocGenElixirGrpc(t, nil, "--help")
	assert.Equal(t, "", stderr.String())
	assert.Equal(t, 0, exitCode)
	assert.Contains(t, stdout.String(), "Flags:")
	assert.Contains(t, stdout.String(), "--version")
	assert.Contains(t, stdout.String(), "--handler_module_prefix")
	assert.Contains(t, stdout.String(), "--server_module_prefix")
}

func TestGenerate(t *testing.T) {
	t.Parallel()

	compilerVersion := &pluginpb.Version{
		Major:  ptr(int32(0)),
		Minor:  ptr(int32(0)),
		Patch:  ptr(int32(1)),
		Suffix: ptr("test"),
	}

	t.Run("basic generation", func(t *testing.T) {
		t.Parallel()

		t.Run("with unary and streaming methods", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("greeter/v1/greeter.proto"),
				Package: ptr("greeter.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("HelloRequest")},
					{Name: ptr("HelloResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("GreeterService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("SayHello"),
								InputType:  ptr(".greeter.v1.HelloRequest"),
								OutputType: ptr(".greeter.v1.HelloResponse"),
							},
							{
								Name:            ptr("SayHelloStream"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(false),
								ServerStreaming: ptr(true),
							},
							{
								Name:            ptr("SayHelloClientStream"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(true),
								ServerStreaming: ptr(false),
							},
							{
								Name:            ptr("SayHelloBidiStream"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(true),
								ServerStreaming: ptr(true),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"greeter/v1/greeter.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "greeter/v1/greeter.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: greeter/v1/greeter.proto

defmodule Greeter.V1.GreeterService.Server do
  use GRPC.Server,
    service: Greeter.V1.GreeterService.Service

  defdelegate say_hello(request, stream),
    to: Greeter.V1.GreeterService.Server.SayHelloHandler,
    as: :handle_message

  defdelegate say_hello_bidi_stream(request_stream, response_stream),
    to: Greeter.V1.GreeterService.Server.SayHelloBidiStreamHandler,
    as: :handle_message

  defdelegate say_hello_client_stream(request_stream, stream),
    to: Greeter.V1.GreeterService.Server.SayHelloClientStreamHandler,
    as: :handle_message

  defdelegate say_hello_stream(request, response_stream),
    to: Greeter.V1.GreeterService.Server.SayHelloStreamHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with methods in reverse alphabetical order", func(t *testing.T) {
			t.Parallel()

			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("greeter/v1/greeter.proto"),
				Package: ptr("greeter.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("HelloRequest")},
					{Name: ptr("HelloResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("GreeterService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:            ptr("Zebra"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(false),
								ServerStreaming: ptr(false),
							},
							{
								Name:            ptr("Yankee"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(false),
								ServerStreaming: ptr(false),
							},
							{
								Name:            ptr("Xray"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(false),
								ServerStreaming: ptr(false),
							},
							{
								Name:            ptr("Alpha"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(false),
								ServerStreaming: ptr(false),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"greeter/v1/greeter.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			content := rsp.File[0].GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: greeter/v1/greeter.proto

defmodule Greeter.V1.GreeterService.Server do
  use GRPC.Server,
    service: Greeter.V1.GreeterService.Service

  defdelegate alpha(request, stream),
    to: Greeter.V1.GreeterService.Server.AlphaHandler,
    as: :handle_message

  defdelegate xray(request, stream),
    to: Greeter.V1.GreeterService.Server.XrayHandler,
    as: :handle_message

  defdelegate yankee(request, stream),
    to: Greeter.V1.GreeterService.Server.YankeeHandler,
    as: :handle_message

  defdelegate zebra(request, stream),
    to: Greeter.V1.GreeterService.Server.ZebraHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with custom handler module prefix", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("auth/v1/auth.proto"),
				Package: ptr("auth.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("LoginRequest")},
					{Name: ptr("LoginResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("AuthService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("Login"),
								InputType:  ptr(".auth.v1.LoginRequest"),
								OutputType: ptr(".auth.v1.LoginResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"auth/v1/auth.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("handler_module_prefix=MyApp.Handlers"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "auth/v1/auth.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: auth/v1/auth.proto

defmodule Auth.V1.AuthService.Server do
  use GRPC.Server,
    service: Auth.V1.AuthService.Service

  defdelegate login(request, stream),
    to: MyApp.Handlers.Auth.V1.AuthService.Server.LoginHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with http_transcode option", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("api/v1/api.proto"),
				Package: ptr("api.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("GetRequest")},
					{Name: ptr("GetResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("ApiService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("Get"),
								InputType:  ptr(".api.v1.GetRequest"),
								OutputType: ptr(".api.v1.GetResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"api/v1/api.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("http_transcode=true"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "api/v1/api.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: api/v1/api.proto

defmodule Api.V1.ApiService.Server do
  use GRPC.Server,
    service: Api.V1.ApiService.Service,
    http_transcode: true

  defdelegate get(request, stream),
    to: Api.V1.ApiService.Server.GetHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with package prefix", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("user.proto"),
				Package: ptr("user.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("GetUserRequest")},
					{Name: ptr("GetUserResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("UserService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("GetUser"),
								InputType:  ptr(".user.v1.GetUserRequest"),
								OutputType: ptr(".user.v1.GetUserResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"user.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("package_prefix=lib/proto"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "lib/proto/user/v1/user.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: user.proto

defmodule User.V1.UserService.Server do
  use GRPC.Server,
    service: User.V1.UserService.Service

  defdelegate get_user(request, stream),
    to: User.V1.UserService.Server.GetUserHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with multiple parameters", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("billing/v1/billing.proto"),
				Package: ptr("billing.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("CreateInvoiceRequest")},
					{Name: ptr("CreateInvoiceResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("BillingService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("CreateInvoice"),
								InputType:  ptr(".billing.v1.CreateInvoiceRequest"),
								OutputType: ptr(".billing.v1.CreateInvoiceResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"billing/v1/billing.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("package_prefix=lib/grpc,handler_module_prefix=MyApp.BusinessLogic"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "lib/grpc/billing/v1/billing.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: billing/v1/billing.proto

defmodule Billing.V1.BillingService.Server do
  use GRPC.Server,
    service: Billing.V1.BillingService.Service

  defdelegate create_invoice(request, stream),
    to: MyApp.BusinessLogic.Billing.V1.BillingService.Server.CreateInvoiceHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with server_module_prefix", func(t *testing.T) {
			t.Parallel()

			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("payment/v1/payment.proto"),
				Package: ptr("payment.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("ChargeRequest")},
					{Name: ptr("ChargeResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("PaymentService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("Charge"),
								InputType:  ptr(".payment.v1.ChargeRequest"),
								OutputType: ptr(".payment.v1.ChargeResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"payment/v1/payment.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("server_module_prefix=MyApp.Grpc"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "payment/v1/payment.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: payment/v1/payment.proto

defmodule MyApp.Grpc.Payment.V1.PaymentService.Server do
  use GRPC.Server,
    service: Payment.V1.PaymentService.Service

  defdelegate charge(request, stream),
    to: Payment.V1.PaymentService.Server.ChargeHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

	t.Run("with server_module_prefix and handler_module_prefix", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name:    ptr("invoice/v1/invoice.proto"),
			Package: ptr("invoice.v1"),
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: ptr("CreateInvoiceRequest")},
				{Name: ptr("CreateInvoiceResponse")},
			},
			Service: []*descriptorpb.ServiceDescriptorProto{
				{
					Name: ptr("InvoiceService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("CreateInvoice"),
							InputType:  ptr(".invoice.v1.CreateInvoiceRequest"),
							OutputType: ptr(".invoice.v1.CreateInvoiceResponse"),
						},
					},
				},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"invoice/v1/invoice.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
			Parameter:             ptr("server_module_prefix=MyApp.Servers,handler_module_prefix=MyApp.Handlers"),
		}

		rsp := testGenerate(t, req)
		assert.Nil(t, rsp.Error)
		assert.Equal(t, 1, len(rsp.File))

		file := rsp.File[0]
		assert.Equal(t, "invoice/v1/invoice.server.pb.ex", file.GetName())

		content := file.GetContent()
		expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: invoice/v1/invoice.proto

defmodule MyApp.Servers.Invoice.V1.InvoiceService.Server do
  use GRPC.Server,
    service: Invoice.V1.InvoiceService.Service

  defdelegate create_invoice(request, stream),
    to: MyApp.Handlers.Invoice.V1.InvoiceService.Server.CreateInvoiceHandler,
    as: :handle_message
end
`
		assert.Equal(t, expected, content)
	})

	t.Run("with http_transcode and handler_module_prefix", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name:    ptr("payment/v1/payment.proto"),
			Package: ptr("payment.v1"),
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: ptr("ProcessRequest")},
				{Name: ptr("ProcessResponse")},
			},
			Service: []*descriptorpb.ServiceDescriptorProto{
				{
					Name: ptr("PaymentService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("ProcessPayment"),
							InputType:  ptr(".payment.v1.ProcessRequest"),
							OutputType: ptr(".payment.v1.ProcessResponse"),
						},
					},
				},
			},
		}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"payment/v1/payment.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("http_transcode=true,handler_module_prefix=MyApp.Core"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "payment/v1/payment.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: payment/v1/payment.proto

defmodule Payment.V1.PaymentService.Server do
  use GRPC.Server,
    service: Payment.V1.PaymentService.Service,
    http_transcode: true

  defdelegate process_payment(request, stream),
    to: MyApp.Core.Payment.V1.PaymentService.Server.ProcessPaymentHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with codecs option", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("data/v1/data.proto"),
				Package: ptr("data.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("DataRequest")},
					{Name: ptr("DataResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("DataService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("GetData"),
								InputType:  ptr(".data.v1.DataRequest"),
								OutputType: ptr(".data.v1.DataResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"data/v1/data.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("codecs=GRPC.Codec.Proto,GRPC.Codec.WebText,GRPC.Codec.JSON"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "data/v1/data.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: data/v1/data.proto

defmodule Data.V1.DataService.Server do
  use GRPC.Server,
    service: Data.V1.DataService.Service,
    codecs: [GRPC.Codec.Proto, GRPC.Codec.WebText, GRPC.Codec.JSON]

  defdelegate get_data(request, stream),
    to: Data.V1.DataService.Server.GetDataHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with codecs option with spaces", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("content/v1/content.proto"),
				Package: ptr("content.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("ContentRequest")},
					{Name: ptr("ContentResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("ContentService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("GetContent"),
								InputType:  ptr(".content.v1.ContentRequest"),
								OutputType: ptr(".content.v1.ContentResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"content/v1/content.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("codecs=GRPC.Codec.Proto, GRPC.Codec.WebText, GRPC.Codec.JSON"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "content/v1/content.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: content/v1/content.proto

defmodule Content.V1.ContentService.Server do
  use GRPC.Server,
    service: Content.V1.ContentService.Service,
    codecs: [GRPC.Codec.Proto, GRPC.Codec.WebText, GRPC.Codec.JSON]

  defdelegate get_content(request, stream),
    to: Content.V1.ContentService.Server.GetContentHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with compressors option", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("data/v1/data.proto"),
				Package: ptr("data.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("DataRequest")},
					{Name: ptr("DataResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("DataService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("GetData"),
								InputType:  ptr(".data.v1.DataRequest"),
								OutputType: ptr(".data.v1.DataResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"data/v1/data.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("compressors=GRPC.Compressor.Gzip"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "data/v1/data.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: data/v1/data.proto

defmodule Data.V1.DataService.Server do
  use GRPC.Server,
    service: Data.V1.DataService.Service,
    compressors: [GRPC.Compressor.Gzip]

  defdelegate get_data(request, stream),
    to: Data.V1.DataService.Server.GetDataHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with all options combined", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("store/v1/store.proto"),
				Package: ptr("store.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("StoreRequest")},
					{Name: ptr("StoreResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("StoreService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("CreateStore"),
								InputType:  ptr(".store.v1.StoreRequest"),
								OutputType: ptr(".store.v1.StoreResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"store/v1/store.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("http_transcode=true,handler_module_prefix=MyApp.Business,codecs=GRPC.Codec.Proto,GRPC.Codec.JSON,compressors=GRPC.Compressor.Gzip"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "store/v1/store.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: store/v1/store.proto

defmodule Store.V1.StoreService.Server do
  use GRPC.Server,
    service: Store.V1.StoreService.Service,
    http_transcode: true,
    codecs: [GRPC.Codec.Proto, GRPC.Codec.JSON],
    compressors: [GRPC.Compressor.Gzip]

  defdelegate create_store(request, stream),
    to: MyApp.Business.Store.V1.StoreService.Server.CreateStoreHandler,
    as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})
	})

	t.Run("no service", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name:    ptr("messages.proto"),
			Package: ptr("test.v1"),
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: ptr("User")},
				{Name: ptr("Product")},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"messages.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
		}

		rsp := testGenerate(t, req)
		assert.Nil(t, rsp.Error)
		assert.Equal(t, 0, len(rsp.File))
	})

	t.Run("multiple services in same file", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name:    ptr("services.proto"),
			Package: ptr("test.v1"),
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: ptr("UserRequest")},
				{Name: ptr("UserResponse")},
				{Name: ptr("ProductRequest")},
				{Name: ptr("ProductResponse")},
			},
			Service: []*descriptorpb.ServiceDescriptorProto{
				{
					Name: ptr("UserService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("CreateUser"),
							InputType:  ptr(".test.v1.UserRequest"),
							OutputType: ptr(".test.v1.UserResponse"),
						},
					},
				},
				{
					Name: ptr("ProductService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("CreateProduct"),
							InputType:  ptr(".test.v1.ProductRequest"),
							OutputType: ptr(".test.v1.ProductResponse"),
						},
					},
				},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"services.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
		}

		rsp := testGenerate(t, req)
		assert.Nil(t, rsp.Error)
		assert.Equal(t, 1, len(rsp.File))

		file := rsp.File[0]
		assert.Equal(t, "test/v1/services.server.pb.ex", file.GetName())

		content := file.GetContent()
		expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: services.proto

defmodule Test.V1.UserService.Server do
  use GRPC.Server,
    service: Test.V1.UserService.Service

  defdelegate create_user(request, stream),
    to: Test.V1.UserService.Server.CreateUserHandler,
    as: :handle_message
end
defmodule Test.V1.ProductService.Server do
  use GRPC.Server,
    service: Test.V1.ProductService.Service

  defdelegate create_product(request, stream),
    to: Test.V1.ProductService.Server.CreateProductHandler,
    as: :handle_message
end
`
		assert.Equal(t, expected, content)
	})

	t.Run("no package", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name: ptr("simple.proto"),
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: ptr("Request")},
				{Name: ptr("Response")},
			},
			Service: []*descriptorpb.ServiceDescriptorProto{
				{
					Name: ptr("SimpleService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("DoSomething"),
							InputType:  ptr(".Request"),
							OutputType: ptr(".Response"),
						},
					},
				},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"simple.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
		}

		rsp := testGenerate(t, req)
		assert.Nil(t, rsp.Error)
		assert.Equal(t, 1, len(rsp.File))

		file := rsp.File[0]
		assert.Equal(t, "/simple.server.pb.ex", file.GetName())

		content := file.GetContent()
		expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: simple.proto

defmodule SimpleService.Server do
  use GRPC.Server,
    service: SimpleService.Service

  defdelegate do_something(request, stream),
    to: SimpleService.Server.DoSomethingHandler,
    as: :handle_message
end
`
		assert.Equal(t, expected, content)
	})

	t.Run("no package with server_module_prefix", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name: ptr("payment.proto"),
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: ptr("RefundRequest")},
				{Name: ptr("RefundResponse")},
			},
			Service: []*descriptorpb.ServiceDescriptorProto{
				{
					Name: ptr("PaymentService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("Refund"),
							InputType:  ptr(".RefundRequest"),
							OutputType: ptr(".RefundResponse"),
						},
					},
				},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"payment.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
			Parameter:             ptr("server_module_prefix=MyApp.Grpc"),
		}

		rsp := testGenerate(t, req)
		assert.Nil(t, rsp.Error)
		assert.Equal(t, 1, len(rsp.File))

		file := rsp.File[0]
		assert.Equal(t, "/payment.server.pb.ex", file.GetName())

		content := file.GetContent()
		expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: payment.proto

defmodule MyApp.Grpc.PaymentService.Server do
  use GRPC.Server,
    service: PaymentService.Service

  defdelegate refund(request, stream),
    to: PaymentService.Server.RefundHandler,
    as: :handle_message
end
`
		assert.Equal(t, expected, content)
	})

	t.Run("invalid parameters", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name:    ptr("test.proto"),
			Package: ptr("test.v1"),
			Service: []*descriptorpb.ServiceDescriptorProto{
				{
					Name: ptr("TestService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("Test"),
							InputType:  ptr(".test.v1.Request"),
							OutputType: ptr(".test.v1.Response"),
						},
					},
				},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"test.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
			Parameter:             ptr("invalid_flag=value"),
		}

		rsp := testGenerate(t, req)
		assert.NotNil(t, rsp.Error)
		assert.Contains(t, rsp.GetError(), "no such flag")
		assert.Equal(t, 0, len(rsp.File))
	})
}

func TestToSnakeCase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"SayHello", "say_hello"},
		{"SayGoodbye", "say_goodbye"},
		{"HTTPClient", "http_client"},
		{"XMLParser", "xml_parser"},
		{"ID", "id"},
		{"UserID", "user_id"},
		{"GetUserProfile", "get_user_profile"},
		{"", ""},
		{"A", "a"},
		{"AB", "ab"},
	}

	for _, test := range tests {
		t.Run(test.input, func(t *testing.T) {
			result := toSnakeCase(test.input)
			assert.Equal(t, test.expected, result)
		})
	}
}

func TestToPascalCase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"sayHello", "SayHello"},
		{"sayGoodbye", "SayGoodbye"},
		{"httpClient", "HttpClient"},
		{"id", "Id"},
		{"", ""},
		{"a", "A"},
		{"ABC", "ABC"},
		{"SayHello", "SayHello"}, // Already PascalCase
	}

	for _, test := range tests {
		t.Run(test.input, func(t *testing.T) {
			result := toPascalCase(test.input)
			assert.Equal(t, test.expected, result)
		})
	}
}

func TestParseKeyValuePairs(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected map[string]string
	}{
		{
			name:     "empty string",
			input:    "",
			expected: map[string]string{},
		},
		{
			name:     "single key-value",
			input:    "key1=value1",
			expected: map[string]string{"key1": "value1"},
		},
		{
			name:     "single key-value with trailing comma",
			input:    "key1=value1,",
			expected: map[string]string{"key1": "value1"},
		},
		{
			name:     "multiple key-values",
			input:    "key1=value1,key2=value2",
			expected: map[string]string{"key1": "value1", "key2": "value2"},
		},
		{
			name:     "multiple key-values with trailing comma",
			input:    "key1=value1,key2=value2,",
			expected: map[string]string{"key1": "value1", "key2": "value2"},
		},
		{
			name:     "value with commas (codecs)",
			input:    "codecs=A,B,C",
			expected: map[string]string{"codecs": "A,B,C"},
		},
		{
			name:     "value with commas and trailing comma",
			input:    "codecs=A,B,C,",
			expected: map[string]string{"codecs": "A,B,C"},
		},
		{
			name:     "mixed: regular key and value with commas",
			input:    "key1=value1,codecs=A,B,C",
			expected: map[string]string{"key1": "value1", "codecs": "A,B,C"},
		},
		{
			name:     "mixed with trailing comma",
			input:    "key1=value1,codecs=A,B,C,",
			expected: map[string]string{"key1": "value1", "codecs": "A,B,C"},
		},
		{
			name:     "with spaces",
			input:    "key1 = value1 , key2 = value2",
			expected: map[string]string{"key1": "value1", "key2": "value2"},
		},
		{
			name:     "multiple trailing commas",
			input:    "key1=value1,,,",
			expected: map[string]string{"key1": "value1"},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := parseKeyValuePairs(test.input)
			assert.Equal(t, test.expected, result)
		})
	}
}

func TestParseCodecs(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected []string
	}{
		{
			name:     "empty string",
			input:    "",
			expected: nil,
		},
		{
			name:     "single codec",
			input:    "GRPC.Codec.Proto",
			expected: []string{"GRPC.Codec.Proto"},
		},
		{
			name:     "multiple codecs",
			input:    "GRPC.Codec.Proto,GRPC.Codec.WebText,GRPC.Codec.JSON",
			expected: []string{"GRPC.Codec.Proto", "GRPC.Codec.WebText", "GRPC.Codec.JSON"},
		},
		{
			name:     "multiple codecs with spaces",
			input:    "GRPC.Codec.Proto, GRPC.Codec.WebText, GRPC.Codec.JSON",
			expected: []string{"GRPC.Codec.Proto", "GRPC.Codec.WebText", "GRPC.Codec.JSON"},
		},
		{
			name:     "with extra spaces",
			input:    " GRPC.Codec.Proto ,  GRPC.Codec.WebText  ,GRPC.Codec.JSON ",
			expected: []string{"GRPC.Codec.Proto", "GRPC.Codec.WebText", "GRPC.Codec.JSON"},
		},
		{
			name:     "with empty items",
			input:    "GRPC.Codec.Proto,,,GRPC.Codec.JSON",
			expected: []string{"GRPC.Codec.Proto", "GRPC.Codec.JSON"},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := parseCodecs(test.input)
			assert.Equal(t, test.expected, result)
		})
	}
}

func testGenerate(t *testing.T, req *pluginpb.CodeGeneratorRequest) *pluginpb.CodeGeneratorResponse {
	t.Helper()

	inputBytes, err := proto.Marshal(req)
	require.NoError(t, err)

	stdout, stderr, exitCode := testRunProtocGenElixirGrpc(t, bytes.NewReader(inputBytes))
	if exitCode != 0 {
		t.Errorf("Plugin failed with exit code %d, stderr: %s", exitCode, stderr.String())
		return nil
	}
	assert.Equal(t, 0, exitCode)
	assert.Equal(t, "", stderr.String())
	assert.Greater(t, len(stdout.Bytes()), 0)

	var output pluginpb.CodeGeneratorResponse
	assert.NoError(t, proto.Unmarshal(stdout.Bytes(), &output))
	return &output
}

func testRunProtocGenElixirGrpc(t *testing.T, stdin io.Reader, args ...string) (stdout, stderr *bytes.Buffer, exitCode int) {
	t.Helper()

	stdout = &bytes.Buffer{}
	stderr = &bytes.Buffer{}
	args = append([]string{"run", "main.go"}, args...)

	cmd := exec.Command("go", args...)
	cmd.Env = os.Environ()
	cmd.Stdin = stdin
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	_ = cmd.Run() // Don't use require.NoError since we want to capture exit codes
	exitCode = cmd.ProcessState.ExitCode()
	return stdout, stderr, exitCode
}

func ptr[T any](v T) *T {
	return &v
}
