package main

import (
	"bytes"
	"io"
	"os"
	"os/exec"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestVersion(t *testing.T) {
	t.Parallel()
	stdout, stderr, exitCode := testRunProtocGenElixirGrpc(t, nil, "--version")
	assert.Equal(t, "", stderr.String())
	assert.Equal(t, 0, exitCode)
	assert.Contains(t, stdout.String(), "protoc-gen-elixir-grpc")
	assert.Contains(t, stdout.String(), "commit:")
	assert.Contains(t, stdout.String(), "built:")
}

func TestHelp(t *testing.T) {
	t.Parallel()
	stdout, stderr, exitCode := testRunProtocGenElixirGrpc(t, nil, "--help")
	assert.Equal(t, "", stderr.String())
	assert.Equal(t, 0, exitCode)
	assert.Contains(t, stdout.String(), "Flags:")
	assert.Contains(t, stdout.String(), "--version")
	assert.Contains(t, stdout.String(), "--handler_module_prefix")
}

func TestGenerate(t *testing.T) {
	t.Parallel()

	compilerVersion := &pluginpb.Version{
		Major:  ptr(int32(0)),
		Minor:  ptr(int32(0)),
		Patch:  ptr(int32(1)),
		Suffix: ptr("test"),
	}

	t.Run("basic generation", func(t *testing.T) {
		t.Parallel()

		t.Run("with unary and streaming methods", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("greeter/v1/greeter.proto"),
				Package: ptr("greeter.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("HelloRequest")},
					{Name: ptr("HelloResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("GreeterService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("SayHello"),
								InputType:  ptr(".greeter.v1.HelloRequest"),
								OutputType: ptr(".greeter.v1.HelloResponse"),
							},
							{
								Name:            ptr("SayHelloStream"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(false),
								ServerStreaming: ptr(true),
							},
							{
								Name:            ptr("SayHelloClientStream"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(true),
								ServerStreaming: ptr(false),
							},
							{
								Name:            ptr("SayHelloBidiStream"),
								InputType:       ptr(".greeter.v1.HelloRequest"),
								OutputType:      ptr(".greeter.v1.HelloResponse"),
								ClientStreaming: ptr(true),
								ServerStreaming: ptr(true),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"greeter/v1/greeter.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "greeter/v1/greeter.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: greeter/v1/greeter.proto

defmodule Greeter.V1.GreeterService.Server do
  use GRPC.Server, service: Greeter.V1.GreeterService.Service

  defdelegate say_hello(request, stream), to: Greeter.V1.GreeterService.Server.SayHelloHandler, as: :handle_message
  defdelegate say_hello_stream(request, response_stream), to: Greeter.V1.GreeterService.Server.SayHelloStreamHandler, as: :handle_message
  defdelegate say_hello_client_stream(request_stream, stream), to: Greeter.V1.GreeterService.Server.SayHelloClientStreamHandler, as: :handle_message
  defdelegate say_hello_bidi_stream(request_stream, response_stream), to: Greeter.V1.GreeterService.Server.SayHelloBidiStreamHandler, as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with custom handler module prefix", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("auth/v1/auth.proto"),
				Package: ptr("auth.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("LoginRequest")},
					{Name: ptr("LoginResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("AuthService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("Login"),
								InputType:  ptr(".auth.v1.LoginRequest"),
								OutputType: ptr(".auth.v1.LoginResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"auth/v1/auth.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("handler_module_prefix=MyApp.Handlers"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "auth/v1/auth.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: auth/v1/auth.proto

defmodule Auth.V1.AuthService.Server do
  use GRPC.Server, service: Auth.V1.AuthService.Service

  defdelegate login(request, stream), to: MyApp.Handlers.Auth.V1.AuthService.Server.LoginHandler, as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with http_transcode option", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("api/v1/api.proto"),
				Package: ptr("api.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("GetRequest")},
					{Name: ptr("GetResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("ApiService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("Get"),
								InputType:  ptr(".api.v1.GetRequest"),
								OutputType: ptr(".api.v1.GetResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"api/v1/api.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("http_transcode=true"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "api/v1/api.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: api/v1/api.proto

defmodule Api.V1.ApiService.Server do
  use GRPC.Server, service: Api.V1.ApiService.Service, http_transcode: true

  defdelegate get(request, stream), to: Api.V1.ApiService.Server.GetHandler, as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with package prefix", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("user.proto"),
				Package: ptr("user.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("GetUserRequest")},
					{Name: ptr("GetUserResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("UserService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("GetUser"),
								InputType:  ptr(".user.v1.GetUserRequest"),
								OutputType: ptr(".user.v1.GetUserResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"user.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("package_prefix=lib/proto"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "lib/proto/user/v1/user.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: user.proto

defmodule User.V1.UserService.Server do
  use GRPC.Server, service: User.V1.UserService.Service

  defdelegate get_user(request, stream), to: User.V1.UserService.Server.GetUserHandler, as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with multiple parameters", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("billing/v1/billing.proto"),
				Package: ptr("billing.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("CreateInvoiceRequest")},
					{Name: ptr("CreateInvoiceResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("BillingService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("CreateInvoice"),
								InputType:  ptr(".billing.v1.CreateInvoiceRequest"),
								OutputType: ptr(".billing.v1.CreateInvoiceResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"billing/v1/billing.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("package_prefix=lib/grpc,handler_module_prefix=MyApp.BusinessLogic"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "lib/grpc/billing/v1/billing.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: billing/v1/billing.proto

defmodule Billing.V1.BillingService.Server do
  use GRPC.Server, service: Billing.V1.BillingService.Service

  defdelegate create_invoice(request, stream), to: MyApp.BusinessLogic.Billing.V1.BillingService.Server.CreateInvoiceHandler, as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})

		t.Run("with http_transcode and handler_module_prefix", func(t *testing.T) {
			fileDesc := &descriptorpb.FileDescriptorProto{
				Name:    ptr("payment/v1/payment.proto"),
				Package: ptr("payment.v1"),
				MessageType: []*descriptorpb.DescriptorProto{
					{Name: ptr("ProcessRequest")},
					{Name: ptr("ProcessResponse")},
				},
				Service: []*descriptorpb.ServiceDescriptorProto{
					{
						Name: ptr("PaymentService"),
						Method: []*descriptorpb.MethodDescriptorProto{
							{
								Name:       ptr("ProcessPayment"),
								InputType:  ptr(".payment.v1.ProcessRequest"),
								OutputType: ptr(".payment.v1.ProcessResponse"),
							},
						},
					},
				},
			}

			req := &pluginpb.CodeGeneratorRequest{
				FileToGenerate:        []string{"payment/v1/payment.proto"},
				ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
				SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
				CompilerVersion:       compilerVersion,
				Parameter:             ptr("http_transcode=true,handler_module_prefix=MyApp.Core"),
			}

			rsp := testGenerate(t, req)
			assert.Nil(t, rsp.Error)
			assert.Equal(t, 1, len(rsp.File))

			file := rsp.File[0]
			assert.Equal(t, "payment/v1/payment.server.pb.ex", file.GetName())

			content := file.GetContent()
			expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: payment/v1/payment.proto

defmodule Payment.V1.PaymentService.Server do
  use GRPC.Server, service: Payment.V1.PaymentService.Service, http_transcode: true

  defdelegate process_payment(request, stream), to: MyApp.Core.Payment.V1.PaymentService.Server.ProcessPaymentHandler, as: :handle_message
end
`
			assert.Equal(t, expected, content)
		})
	})

	t.Run("no service", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name:    ptr("messages.proto"),
			Package: ptr("test.v1"),
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: ptr("User")},
				{Name: ptr("Product")},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"messages.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
		}

		rsp := testGenerate(t, req)
		assert.Nil(t, rsp.Error)
		assert.Equal(t, 0, len(rsp.File))
	})

	t.Run("multiple services in same file", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name:    ptr("services.proto"),
			Package: ptr("test.v1"),
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: ptr("UserRequest")},
				{Name: ptr("UserResponse")},
				{Name: ptr("ProductRequest")},
				{Name: ptr("ProductResponse")},
			},
			Service: []*descriptorpb.ServiceDescriptorProto{
				{
					Name: ptr("UserService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("CreateUser"),
							InputType:  ptr(".test.v1.UserRequest"),
							OutputType: ptr(".test.v1.UserResponse"),
						},
					},
				},
				{
					Name: ptr("ProductService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("CreateProduct"),
							InputType:  ptr(".test.v1.ProductRequest"),
							OutputType: ptr(".test.v1.ProductResponse"),
						},
					},
				},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"services.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
		}

		rsp := testGenerate(t, req)
		assert.Nil(t, rsp.Error)
		assert.Equal(t, 1, len(rsp.File))

		file := rsp.File[0]
		assert.Equal(t, "test/v1/services.server.pb.ex", file.GetName())

		content := file.GetContent()
		expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: services.proto

defmodule Test.V1.UserService.Server do
  use GRPC.Server, service: Test.V1.UserService.Service

  defdelegate create_user(request, stream), to: Test.V1.UserService.Server.CreateUserHandler, as: :handle_message
end
defmodule Test.V1.ProductService.Server do
  use GRPC.Server, service: Test.V1.ProductService.Service

  defdelegate create_product(request, stream), to: Test.V1.ProductService.Server.CreateProductHandler, as: :handle_message
end
`
		assert.Equal(t, expected, content)
	})

	t.Run("no package", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name: ptr("simple.proto"),
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: ptr("Request")},
				{Name: ptr("Response")},
			},
			Service: []*descriptorpb.ServiceDescriptorProto{
				{
					Name: ptr("SimpleService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("DoSomething"),
							InputType:  ptr(".Request"),
							OutputType: ptr(".Response"),
						},
					},
				},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"simple.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
		}

		rsp := testGenerate(t, req)
		assert.Nil(t, rsp.Error)
		assert.Equal(t, 1, len(rsp.File))

		file := rsp.File[0]
		assert.Equal(t, "/simple.server.pb.ex", file.GetName())

		content := file.GetContent()
		expected := `# Code generated by protoc-gen-elixir-grpc. DO NOT EDIT.
#
# Source: simple.proto

defmodule SimpleService.Server do
  use GRPC.Server, service: SimpleService.Service

  defdelegate do_something(request, stream), to: SimpleService.Server.DoSomethingHandler, as: :handle_message
end
`
		assert.Equal(t, expected, content)
	})

	t.Run("invalid parameters", func(t *testing.T) {
		t.Parallel()

		fileDesc := &descriptorpb.FileDescriptorProto{
			Name:    ptr("test.proto"),
			Package: ptr("test.v1"),
			Service: []*descriptorpb.ServiceDescriptorProto{
				{
					Name: ptr("TestService"),
					Method: []*descriptorpb.MethodDescriptorProto{
						{
							Name:       ptr("Test"),
							InputType:  ptr(".test.v1.Request"),
							OutputType: ptr(".test.v1.Response"),
						},
					},
				},
			},
		}

		req := &pluginpb.CodeGeneratorRequest{
			FileToGenerate:        []string{"test.proto"},
			ProtoFile:             []*descriptorpb.FileDescriptorProto{fileDesc},
			SourceFileDescriptors: []*descriptorpb.FileDescriptorProto{fileDesc},
			CompilerVersion:       compilerVersion,
			Parameter:             ptr("invalid_flag=value"),
		}

		rsp := testGenerate(t, req)
		assert.NotNil(t, rsp.Error)
		assert.Contains(t, rsp.GetError(), "no such flag")
		assert.Equal(t, 0, len(rsp.File))
	})
}

func TestToSnakeCase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"SayHello", "say_hello"},
		{"SayGoodbye", "say_goodbye"},
		{"HTTPClient", "http_client"},
		{"XMLParser", "xml_parser"},
		{"ID", "id"},
		{"UserID", "user_id"},
		{"GetUserProfile", "get_user_profile"},
		{"", ""},
		{"A", "a"},
		{"AB", "ab"},
	}

	for _, test := range tests {
		t.Run(test.input, func(t *testing.T) {
			result := toSnakeCase(test.input)
			assert.Equal(t, test.expected, result)
		})
	}
}

func TestToPascalCase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"sayHello", "SayHello"},
		{"sayGoodbye", "SayGoodbye"},
		{"httpClient", "HttpClient"},
		{"id", "Id"},
		{"", ""},
		{"a", "A"},
		{"ABC", "ABC"},
		{"SayHello", "SayHello"}, // Already PascalCase
	}

	for _, test := range tests {
		t.Run(test.input, func(t *testing.T) {
			result := toPascalCase(test.input)
			assert.Equal(t, test.expected, result)
		})
	}
}

func testGenerate(t *testing.T, req *pluginpb.CodeGeneratorRequest) *pluginpb.CodeGeneratorResponse {
	t.Helper()

	inputBytes, err := proto.Marshal(req)
	require.NoError(t, err)

	stdout, stderr, exitCode := testRunProtocGenElixirGrpc(t, bytes.NewReader(inputBytes))
	if exitCode != 0 {
		t.Errorf("Plugin failed with exit code %d, stderr: %s", exitCode, stderr.String())
		return nil
	}
	assert.Equal(t, 0, exitCode)
	assert.Equal(t, "", stderr.String())
	assert.Greater(t, len(stdout.Bytes()), 0)

	var output pluginpb.CodeGeneratorResponse
	assert.NoError(t, proto.Unmarshal(stdout.Bytes(), &output))
	return &output
}

func testRunProtocGenElixirGrpc(t *testing.T, stdin io.Reader, args ...string) (stdout, stderr *bytes.Buffer, exitCode int) {
	t.Helper()

	stdout = &bytes.Buffer{}
	stderr = &bytes.Buffer{}
	args = append([]string{"run", "main.go"}, args...)

	cmd := exec.Command("go", args...)
	cmd.Env = os.Environ()
	cmd.Stdin = stdin
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	_ = cmd.Run() // Don't use require.NoError since we want to capture exit codes
	exitCode = cmd.ProcessState.ExitCode()
	return stdout, stderr, exitCode
}

func ptr[T any](v T) *T {
	return &v
}
