package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateFile emits one `.pony` source per `.proto` input. Pony has no
// notion of a `package` keyword inside the file (packages are directories),
// so we just stream each top-level message in the file. Nested messages
// flatten with `_` (Outer_Inner) — see collectAndEmitMessages.
//
// Output path mirrors the proto file's path layout (e.g.
// `acme/users/v1/user.proto` → `acme/users/v1/user.pony`). We compute it
// from file.Desc.Path() directly because protogen's GeneratedFilenamePrefix
// is prefixed with the Go import path, which is irrelevant for Pony output.
func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	if len(file.Messages) == 0 && len(file.Enums) == 0 {
		return
	}
	outPath := strings.TrimSuffix(file.Desc.Path(), ".proto") + ".pony"
	g := plugin.NewGeneratedFile(outPath, protogen.GoImportPath(""))

	// Use `//` not `"""` — Pony allows only one package docstring per
	// directory, and the runtime's protobuf.pony already owns it.
	g.P(`// Generated by protoc-gen-pony. DO NOT EDIT.`)
	g.P(`// Source: `, file.Desc.Path())
	g.P()

	collectAndEmitMessages(g, file.Messages, "")
	for _, enum := range file.Enums {
		emitEnumTodo(g, enum, "")
	}
}

// collectAndEmitMessages walks a slice of messages depth-first, flattening
// nested types into their parent's namespace via `Outer_Inner` mangling.
// Messages are emitted in source order — protogen already gives us a
// deterministic walk, so we don't need to sort.
func collectAndEmitMessages(g *protogen.GeneratedFile, messages []*protogen.Message, namePrefix string) {
	for _, msg := range messages {
		flatName := namePrefix + string(msg.Desc.Name())
		emitMessage(g, msg, flatName)
		if len(msg.Messages) > 0 {
			collectAndEmitMessages(g, msg.Messages, flatName+"_")
		}
		for _, enum := range msg.Enums {
			emitEnumTodo(g, enum, flatName+"_")
		}
	}
}

func emitMessage(g *protogen.GeneratedFile, msg *protogen.Message, className string) {
	supported, unsupported := classifyFields(msg.Fields)

	emitClass(g, className, msg.Fields, supported, unsupported)
	g.P()
	emitCodec(g, className, supported)
	g.P()
}

func emitClass(g *protogen.GeneratedFile, className string, all []*protogen.Field, supported, unsupported []*protogen.Field) {
	g.P(`class val `, className)
	for _, field := range all {
		if isSupported(field) {
			g.P(`  let `, fieldName(field), `: `, ponyType(field))
		} else {
			g.P(`  // TODO protoc-gen-pony: field `, fieldName(field), ` (`, fieldShape(field), `)`)
		}
	}
	g.P()
	emitConstructor(g, supported)
	_ = unsupported
}

func emitConstructor(g *protogen.GeneratedFile, supported []*protogen.Field) {
	if len(supported) == 0 {
		g.P(`  new val create() => None`)
		return
	}
	g.P(`  new val create(`)
	for i, field := range supported {
		suffix := ","
		if i == len(supported)-1 {
			suffix = ")"
		}
		g.P(`    `, fieldName(field), `': `, ponyType(field), ` = `, ponyDefault(field), suffix)
	}
	g.P(`  =>`)
	for _, field := range supported {
		g.P(`    `, fieldName(field), ` = `, fieldName(field), `'`)
	}
}

func emitCodec(g *protogen.GeneratedFile, className string, supported []*protogen.Field) {
	g.P(`primitive `, className, `Codec`)
	emitDecode(g, className, supported)
	g.P()
	emitEncode(g, className, supported)
}

func emitDecode(g *protogen.GeneratedFile, className string, supported []*protogen.Field) {
	g.P(`  fun decode(reader: WireReader ref): (`, className, ` val | WireError) =>`)
	for _, field := range supported {
		g.P(`    var `, fieldName(field), `: `, ponyType(field), ` = `, ponyDefault(field))
	}
	g.P(`    while not reader.at_end() do`)
	g.P(`      match reader.read_tag()`)
	g.P(`      | let t: Tag =>`)
	g.P(`        match (t.field_number, t.wire_type)`)
	for _, field := range supported {
		g.P(`        | (`, field.Desc.Number(), `, `, ponyWireType(field), `) =>`)
		g.P(`          match `, ponyReadExpr(field))
		g.P(`          | let v: `, ponyType(field), ` => `, fieldName(field), ` = v`)
		g.P(`          | let e: WireError => return e`)
		g.P(`          end`)
	}
	g.P(`        else`)
	g.P(`          match reader.skip(t.wire_type)`)
	g.P(`          | None => None`)
	g.P(`          | let e: WireError => return e`)
	g.P(`          end`)
	g.P(`        end`)
	g.P(`      | let e: WireError => return e`)
	g.P(`      end`)
	g.P(`    end`)
	emitConstructorCall(g, className, supported)
}

func emitConstructorCall(g *protogen.GeneratedFile, className string, supported []*protogen.Field) {
	if len(supported) == 0 {
		g.P(`    `, className)
		return
	}
	parts := make([]string, len(supported))
	for i, field := range supported {
		parts[i] = fieldName(field)
	}
	g.P(`    `, className, `(`, strings.Join(parts, ", "), `)`)
}

func emitEncode(g *protogen.GeneratedFile, className string, supported []*protogen.Field) {
	g.P(`  fun encode(writer: WireWriter ref, msg: `, className, ` val) =>`)
	if len(supported) == 0 {
		g.P(`    None`)
		return
	}
	for _, field := range supported {
		emitEncodeField(g, field)
	}
}

func emitEncodeField(g *protogen.GeneratedFile, field *protogen.Field) {
	num := field.Desc.Number()
	if field.Desc.Kind() == protoreflect.StringKind {
		// write_string_field handles the empty-string skip internally.
		g.P(`    writer.write_string_field(`, num, `, msg.`, fieldName(field), `)`)
		return
	}
	g.P(`    if `, presenceCheck(field), ` then`)
	g.P(`      writer.write_tag(Tag(`, num, `, `, ponyWireType(field), `))`)
	g.P(`      `, ponyWriteCall(field, "msg."+fieldName(field)))
	g.P(`    end`)
}

// emitEnumTodo lays down a placeholder for enums until enum codegen lands.
func emitEnumTodo(g *protogen.GeneratedFile, enum *protogen.Enum, namePrefix string) {
	g.P(`// TODO protoc-gen-pony: enum `, namePrefix, enum.Desc.Name())
	g.P()
}

// ── classifiers ─────────────────────────────────────────────────────────

// isSupported is the v1 cut: singular implicit-presence proto3 scalars only.
// Repeated, optional explicit presence, oneofs, maps, messages, enums, and
// groups all surface as TODO comments until the corresponding codegen lands.
func isSupported(field *protogen.Field) bool {
	if field.Desc.IsList() || field.Desc.IsMap() {
		return false
	}
	if field.Desc.HasPresence() && !field.Desc.HasOptionalKeyword() {
		// Editions field with explicit presence; defer until presence codegen.
		// (HasOptionalKeyword catches the proto3 `optional` case below.)
	}
	if field.Desc.HasOptionalKeyword() {
		return false
	}
	if field.Oneof != nil && !field.Desc.HasOptionalKeyword() {
		return false
	}
	switch field.Desc.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind, protoreflect.EnumKind:
		return false
	}
	return true
}

func classifyFields(fields []*protogen.Field) (supported, unsupported []*protogen.Field) {
	for _, f := range fields {
		if isSupported(f) {
			supported = append(supported, f)
		} else {
			unsupported = append(unsupported, f)
		}
	}
	return
}

// fieldShape returns a short string describing why a field is unsupported,
// for the TODO comment.
func fieldShape(field *protogen.Field) string {
	parts := []string{}
	if field.Desc.IsMap() {
		parts = append(parts, "map")
	} else if field.Desc.IsList() {
		parts = append(parts, "repeated")
	}
	if field.Desc.HasOptionalKeyword() {
		parts = append(parts, "optional")
	}
	if field.Oneof != nil {
		parts = append(parts, "oneof")
	}
	parts = append(parts, field.Desc.Kind().String())
	return strings.Join(parts, " ")
}

// fieldName returns the Pony-side identifier for a proto field. Proto field
// names are already snake_case so this is the identity for now; the helper
// exists so future name-collision handling lives in one place.
func fieldName(field *protogen.Field) string {
	return string(field.Desc.Name())
}

// ── scalar type lookup ──────────────────────────────────────────────────

func ponyType(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "Bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "I32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "I64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "U32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "U64"
	case protoreflect.FloatKind:
		return "F32"
	case protoreflect.DoubleKind:
		return "F64"
	case protoreflect.StringKind:
		return "String val"
	case protoreflect.BytesKind:
		return "Array[U8] val"
	}
	return ""
}

func ponyDefault(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "false"
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return "0.0"
	case protoreflect.StringKind:
		return `""`
	case protoreflect.BytesKind:
		return "recover val Array[U8] end"
	}
	return "0"
}

func ponyWireType(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
		return "WireFixed32"
	case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind, protoreflect.DoubleKind:
		return "WireFixed64"
	case protoreflect.StringKind, protoreflect.BytesKind:
		return "WireLenDelim"
	}
	return "WireVarint"
}

func ponyReadExpr(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "Scalar.read_bool(reader)"
	case protoreflect.Int32Kind:
		return "Scalar.read_int32(reader)"
	case protoreflect.Int64Kind:
		return "Scalar.read_int64(reader)"
	case protoreflect.Uint32Kind:
		return "Scalar.read_uint32(reader)"
	case protoreflect.Uint64Kind:
		return "Scalar.read_uint64(reader)"
	case protoreflect.Sint32Kind:
		return "Scalar.read_sint32(reader)"
	case protoreflect.Sint64Kind:
		return "Scalar.read_sint64(reader)"
	case protoreflect.Fixed32Kind:
		return "Scalar.read_fixed32(reader)"
	case protoreflect.Fixed64Kind:
		return "Scalar.read_fixed64(reader)"
	case protoreflect.Sfixed32Kind:
		return "Scalar.read_sfixed32(reader)"
	case protoreflect.Sfixed64Kind:
		return "Scalar.read_sfixed64(reader)"
	case protoreflect.FloatKind:
		return "Scalar.read_float(reader)"
	case protoreflect.DoubleKind:
		return "Scalar.read_double(reader)"
	case protoreflect.StringKind:
		return "reader.read_string()"
	case protoreflect.BytesKind:
		return "reader.read_len_delim()"
	}
	return ""
}

func ponyWriteCall(field *protogen.Field, valueRef string) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return fmt.Sprintf("Scalar.write_bool(writer, %s)", valueRef)
	case protoreflect.Int32Kind:
		return fmt.Sprintf("Scalar.write_int32(writer, %s)", valueRef)
	case protoreflect.Int64Kind:
		return fmt.Sprintf("Scalar.write_int64(writer, %s)", valueRef)
	case protoreflect.Uint32Kind:
		return fmt.Sprintf("Scalar.write_uint32(writer, %s)", valueRef)
	case protoreflect.Uint64Kind:
		return fmt.Sprintf("Scalar.write_uint64(writer, %s)", valueRef)
	case protoreflect.Sint32Kind:
		return fmt.Sprintf("Scalar.write_sint32(writer, %s)", valueRef)
	case protoreflect.Sint64Kind:
		return fmt.Sprintf("Scalar.write_sint64(writer, %s)", valueRef)
	case protoreflect.Fixed32Kind:
		return fmt.Sprintf("Scalar.write_fixed32(writer, %s)", valueRef)
	case protoreflect.Fixed64Kind:
		return fmt.Sprintf("Scalar.write_fixed64(writer, %s)", valueRef)
	case protoreflect.Sfixed32Kind:
		return fmt.Sprintf("Scalar.write_sfixed32(writer, %s)", valueRef)
	case protoreflect.Sfixed64Kind:
		return fmt.Sprintf("Scalar.write_sfixed64(writer, %s)", valueRef)
	case protoreflect.FloatKind:
		return fmt.Sprintf("Scalar.write_float(writer, %s)", valueRef)
	case protoreflect.DoubleKind:
		return fmt.Sprintf("Scalar.write_double(writer, %s)", valueRef)
	case protoreflect.BytesKind:
		return fmt.Sprintf("writer.write_len_delim(%s)", valueRef)
	}
	return ""
}

func presenceCheck(field *protogen.Field) string {
	ref := "msg." + fieldName(field)
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return ref
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return ref + " != 0.0"
	case protoreflect.BytesKind:
		return ref + ".size() > 0"
	}
	return ref + " != 0"
}
