package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateFile emits one `.pony` source per `.proto` input. Pony has no
// notion of a `package` keyword inside the file (packages are directories),
// so we just stream each top-level message in the file. Nested messages
// flatten with `_` (Outer_Inner) — see collectAndEmitMessages.
//
// Output path mirrors the proto file's path layout (e.g.
// `acme/users/v1/user.proto` → `acme/users/v1/user.pony`). We compute it
// from file.Desc.Path() directly because protogen's GeneratedFilenamePrefix
// is prefixed with the Go import path, which is irrelevant for Pony output.
func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	if len(file.Messages) == 0 && len(file.Enums) == 0 {
		return
	}
	outPath := strings.TrimSuffix(file.Desc.Path(), ".proto") + ".pony"
	g := plugin.NewGeneratedFile(outPath, protogen.GoImportPath(""))

	// Use `//` not `"""` — Pony allows only one package docstring per
	// directory, and the runtime's protobuf.pony already owns it.
	g.P(`// Generated by protoc-gen-pony. DO NOT EDIT.`)
	g.P(`// Source: `, file.Desc.Path())
	g.P()

	collectAndEmitMessages(g, file.Messages, "")
	for _, enum := range file.Enums {
		emitEnumTodo(g, enum, "")
	}
}

// collectAndEmitMessages walks a slice of messages depth-first, flattening
// nested types into their parent's namespace via `Outer_Inner` mangling.
// Messages are emitted in source order — protogen already gives us a
// deterministic walk, so we don't need to sort.
func collectAndEmitMessages(g *protogen.GeneratedFile, messages []*protogen.Message, namePrefix string) {
	for _, msg := range messages {
		flatName := namePrefix + string(msg.Desc.Name())
		emitMessage(g, msg, flatName)
		if len(msg.Messages) > 0 {
			collectAndEmitMessages(g, msg.Messages, flatName+"_")
		}
		for _, enum := range msg.Enums {
			emitEnumTodo(g, enum, flatName+"_")
		}
	}
}

func emitMessage(g *protogen.GeneratedFile, msg *protogen.Message, className string) {
	supported := supportedFields(msg.Fields)
	emitClass(g, className, msg.Fields, supported)
	g.P()
	emitCodec(g, className, supported)
	g.P()
}

func emitClass(g *protogen.GeneratedFile, className string, all, supported []*protogen.Field) {
	g.P(`class val `, className)
	for _, field := range all {
		if isSupported(field) {
			g.P(`  let `, field.Desc.Name(), `: `, ponyType(field))
		} else {
			g.P(`  // TODO protoc-gen-pony: field `, field.Desc.Name(), ` (`, fieldShape(field), `)`)
		}
	}
	g.P()
	emitConstructor(g, supported)
}

func emitConstructor(g *protogen.GeneratedFile, supported []*protogen.Field) {
	if len(supported) == 0 {
		g.P(`  new val create() => None`)
		return
	}
	g.P(`  new val create(`)
	for i, field := range supported {
		suffix := ","
		if i == len(supported)-1 {
			suffix = ")"
		}
		g.P(`    `, field.Desc.Name(), `': `, ponyType(field), ` = `, ponyDefault(field), suffix)
	}
	g.P(`  =>`)
	for _, field := range supported {
		g.P(`    `, field.Desc.Name(), ` = `, field.Desc.Name(), `'`)
	}
}

func emitCodec(g *protogen.GeneratedFile, className string, supported []*protogen.Field) {
	g.P(`primitive `, className, `Codec`)
	emitDecode(g, className, supported)
	g.P()
	emitEncode(g, className, supported)
}

func emitDecode(g *protogen.GeneratedFile, className string, supported []*protogen.Field) {
	g.P(`  fun decode(reader: WireReader ref): (`, className, ` val | WireError) =>`)
	for _, field := range supported {
		g.P(`    var `, field.Desc.Name(), `: `, ponyType(field), ` = `, ponyDefault(field))
	}
	g.P(`    while not reader.at_end() do`)
	g.P(`      match reader.read_tag()`)
	g.P(`      | let t: Tag =>`)
	g.P(`        match (t.field_number, t.wire_type)`)
	for _, field := range supported {
		g.P(`        | (`, field.Desc.Number(), `, `, ponyWireType(field), `) =>`)
		g.P(`          match `, ponyReadExpr(field))
		g.P(`          | let v: `, ponyType(field), ` => `, field.Desc.Name(), ` = v`)
		g.P(`          | let e: WireError => return e`)
		g.P(`          end`)
	}
	g.P(`        else`)
	g.P(`          match reader.skip(t.wire_type)`)
	g.P(`          | None => None`)
	g.P(`          | let e: WireError => return e`)
	g.P(`          end`)
	g.P(`        end`)
	g.P(`      | let e: WireError => return e`)
	g.P(`      end`)
	g.P(`    end`)
	emitConstructorCall(g, className, supported)
}

func emitConstructorCall(g *protogen.GeneratedFile, className string, supported []*protogen.Field) {
	if len(supported) == 0 {
		g.P(`    `, className)
		return
	}
	parts := make([]string, len(supported))
	for i, field := range supported {
		parts[i] = string(field.Desc.Name())
	}
	g.P(`    `, className, `(`, strings.Join(parts, ", "), `)`)
}

func emitEncode(g *protogen.GeneratedFile, className string, supported []*protogen.Field) {
	g.P(`  fun encode(writer: WireWriter ref, msg: `, className, ` val) =>`)
	if len(supported) == 0 {
		g.P(`    None`)
		return
	}
	for _, field := range supported {
		emitEncodeField(g, field)
	}
}

func emitEncodeField(g *protogen.GeneratedFile, field *protogen.Field) {
	num := field.Desc.Number()
	if field.Desc.Kind() == protoreflect.StringKind {
		// write_string_field handles the empty-string skip internally.
		g.P(`    writer.write_string_field(`, num, `, msg.`, field.Desc.Name(), `)`)
		return
	}
	g.P(`    if `, presenceCheck(field), ` then`)
	g.P(`      writer.write_tag(Tag(`, num, `, `, ponyWireType(field), `))`)
	g.P(`      `, ponyWriteCall(field, "msg."+string(field.Desc.Name())))
	g.P(`    end`)
}

func emitEnumTodo(g *protogen.GeneratedFile, enum *protogen.Enum, namePrefix string) {
	g.P(`// TODO protoc-gen-pony: enum `, namePrefix, enum.Desc.Name())
	g.P()
}

// isSupported is the v1 cut: singular implicit-presence proto3 scalars only.
// Repeated, optional explicit presence (proto3 `optional` and editions
// EXPLICIT presence), oneofs, maps, messages, enums, and groups all surface
// as TODO comments until the corresponding codegen lands.
func isSupported(field *protogen.Field) bool {
	if field.Desc.IsList() || field.Desc.IsMap() {
		return false
	}
	// Editions fields with explicit presence (and proto3 `optional`).
	if field.Desc.HasPresence() {
		return false
	}
	if field.Oneof != nil {
		return false
	}
	switch field.Desc.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind, protoreflect.EnumKind:
		return false
	}
	return true
}

func supportedFields(fields []*protogen.Field) []*protogen.Field {
	var out []*protogen.Field
	for _, f := range fields {
		if isSupported(f) {
			out = append(out, f)
		}
	}
	return out
}

// fieldShape returns a short string describing why a field is unsupported,
// for the TODO comment.
func fieldShape(field *protogen.Field) string {
	parts := []string{}
	if field.Desc.IsMap() {
		parts = append(parts, "map")
	} else if field.Desc.IsList() {
		parts = append(parts, "repeated")
	}
	if field.Desc.HasOptionalKeyword() {
		parts = append(parts, "optional")
	}
	if field.Oneof != nil {
		parts = append(parts, "oneof")
	}
	parts = append(parts, field.Desc.Kind().String())
	return strings.Join(parts, " ")
}

// scalarSpec lookups for Pony codegen. Single source of truth for the
// FieldKind → (Pony type, default, wire type, read expr, write fmt,
// presence-check fmt) mapping. writeFmt and presence are fmt.Sprintf
// patterns with one `%s` for the value reference; an empty writeFmt means
// the kind is special-cased in emitEncodeField (StringKind goes through
// write_string_field). Adding a new Kind requires editing one entry.
type scalarSpec struct {
	ponyType    string
	ponyDefault string
	wireType    string
	readExpr    string
	writeFmt    string
	presence    string
}

var scalarSpecs = map[protoreflect.Kind]scalarSpec{
	protoreflect.BoolKind: {
		ponyType: "Bool", ponyDefault: "false", wireType: "WireVarint",
		readExpr: "Scalar.read_bool(reader)", writeFmt: "Scalar.write_bool(writer, %s)",
		presence: "%s",
	},
	protoreflect.Int32Kind: {
		ponyType: "I32", ponyDefault: "0", wireType: "WireVarint",
		readExpr: "Scalar.read_int32(reader)", writeFmt: "Scalar.write_int32(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.Int64Kind: {
		ponyType: "I64", ponyDefault: "0", wireType: "WireVarint",
		readExpr: "Scalar.read_int64(reader)", writeFmt: "Scalar.write_int64(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.Uint32Kind: {
		ponyType: "U32", ponyDefault: "0", wireType: "WireVarint",
		readExpr: "Scalar.read_uint32(reader)", writeFmt: "Scalar.write_uint32(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.Uint64Kind: {
		ponyType: "U64", ponyDefault: "0", wireType: "WireVarint",
		readExpr: "Scalar.read_uint64(reader)", writeFmt: "Scalar.write_uint64(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.Sint32Kind: {
		ponyType: "I32", ponyDefault: "0", wireType: "WireVarint",
		readExpr: "Scalar.read_sint32(reader)", writeFmt: "Scalar.write_sint32(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.Sint64Kind: {
		ponyType: "I64", ponyDefault: "0", wireType: "WireVarint",
		readExpr: "Scalar.read_sint64(reader)", writeFmt: "Scalar.write_sint64(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.Fixed32Kind: {
		ponyType: "U32", ponyDefault: "0", wireType: "WireFixed32",
		readExpr: "Scalar.read_fixed32(reader)", writeFmt: "Scalar.write_fixed32(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.Fixed64Kind: {
		ponyType: "U64", ponyDefault: "0", wireType: "WireFixed64",
		readExpr: "Scalar.read_fixed64(reader)", writeFmt: "Scalar.write_fixed64(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.Sfixed32Kind: {
		ponyType: "I32", ponyDefault: "0", wireType: "WireFixed32",
		readExpr: "Scalar.read_sfixed32(reader)", writeFmt: "Scalar.write_sfixed32(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.Sfixed64Kind: {
		ponyType: "I64", ponyDefault: "0", wireType: "WireFixed64",
		readExpr: "Scalar.read_sfixed64(reader)", writeFmt: "Scalar.write_sfixed64(writer, %s)",
		presence: "%s != 0",
	},
	protoreflect.FloatKind: {
		ponyType: "F32", ponyDefault: "0.0", wireType: "WireFixed32",
		readExpr: "Scalar.read_float(reader)", writeFmt: "Scalar.write_float(writer, %s)",
		presence: "%s != 0.0",
	},
	protoreflect.DoubleKind: {
		ponyType: "F64", ponyDefault: "0.0", wireType: "WireFixed64",
		readExpr: "Scalar.read_double(reader)", writeFmt: "Scalar.write_double(writer, %s)",
		presence: "%s != 0.0",
	},
	protoreflect.StringKind: {
		ponyType: "String val", ponyDefault: `""`, wireType: "WireLenDelim",
		readExpr: "reader.read_string()",
		// writeFmt empty: emitEncodeField special-cases StringKind through
		// write_string_field. presence empty for the same reason.
	},
	protoreflect.BytesKind: {
		ponyType: "Array[U8] val", ponyDefault: "recover val Array[U8] end", wireType: "WireLenDelim",
		readExpr: "reader.read_len_delim()", writeFmt: "writer.write_len_delim(%s)",
		presence: "%s.size() > 0",
	},
}

func ponyType(field *protogen.Field) string {
	return scalarSpecs[field.Desc.Kind()].ponyType
}

func ponyDefault(field *protogen.Field) string {
	return scalarSpecs[field.Desc.Kind()].ponyDefault
}

func ponyWireType(field *protogen.Field) string {
	return scalarSpecs[field.Desc.Kind()].wireType
}

func ponyReadExpr(field *protogen.Field) string {
	return scalarSpecs[field.Desc.Kind()].readExpr
}

func ponyWriteCall(field *protogen.Field, valueRef string) string {
	spec := scalarSpecs[field.Desc.Kind()]
	if spec.writeFmt == "" {
		return ""
	}
	return fmt.Sprintf(spec.writeFmt, valueRef)
}

func presenceCheck(field *protogen.Field) string {
	spec := scalarSpecs[field.Desc.Kind()]
	return fmt.Sprintf(spec.presence, "msg."+string(field.Desc.Name()))
}
