name: cd

on:
  release:
    types:
      - released
      - prereleased

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish Plugin to BSR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: [protoc-gen-connect-go-servicestruct]

    steps:
      - uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          BUF_TOKEN: "op://k7d773ss2nhgrxqzoru5ozdrla/TrogonStack/BUF_TOKEN"

      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.24.x

      - uses: bufbuild/buf-action@v1.3.0
        with:
          token: ${{ env.BUF_TOKEN }}
          setup_only: true

      - name: Build plugin binaries
        run: |
          GOOS=wasip1 GOARCH=wasm go build -o ${{ matrix.plugin }}.wasm ./cmd/${{ matrix.plugin }}

      - name: Push plugin to BSR
        run: |
          buf plugin push buf.build/trogonstack/${{ matrix.plugin }} \
            --binary=${{ matrix.plugin }}.wasm \
            --create \
            --create-visibility=public \
            --label=${{ github.event.release.tag_name }} \
            --label=latest
